// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTMxKHfglr8ipdYoeNVKXBETdgaJstd4',
    appId: '1:8192017725:web:d3cdba4d6462b810597154',
    messagingSenderId: '8192017725',
    projectId: 'plantpulse-1f963',
    authDomain: 'plantpulse-1f963.firebaseapp.com',
    storageBucket: 'plantpulse-1f963.firebasestorage.app',
    measurementId: 'G-CY4PCGHQL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19T6AnFpSE4soe0Jh5insshtpHSON_2M',
    appId: '1:8192017725:android:a5d075e0cc8648c1597154',
    messagingSenderId: '8192017725',
    projectId: 'plantpulse-1f963',
    storageBucket: 'plantpulse-1f963.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrk5loJ3pJeChPjswMIT7DmYiYqKIaJT4',
    appId: '1:8192017725:ios:224d670bc1f3ce51597154',
    messagingSenderId: '8192017725',
    projectId: 'plantpulse-1f963',
    storageBucket: 'plantpulse-1f963.firebasestorage.app',
    iosBundleId: 'com.example.plantpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrk5loJ3pJeChPjswMIT7DmYiYqKIaJT4',
    appId: '1:8192017725:ios:224d670bc1f3ce51597154',
    messagingSenderId: '8192017725',
    projectId: 'plantpulse-1f963',
    storageBucket: 'plantpulse-1f963.firebasestorage.app',
    iosBundleId: 'com.example.plantpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDTMxKHfglr8ipdYoeNVKXBETdgaJstd4',
    appId: '1:8192017725:web:856e79103e272d5a597154',
    messagingSenderId: '8192017725',
    projectId: 'plantpulse-1f963',
    authDomain: 'plantpulse-1f963.firebaseapp.com',
    storageBucket: 'plantpulse-1f963.firebasestorage.app',
    measurementId: 'G-ED04HW3NNW',
  );
}
